spring:
  application:
    name: linkstack
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax

vaadin:
  launch-browser: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
